### ISSUE TITLE
add vuejs file icon

### ISSUE THREAD

**Issue by EDiaos** [jesseweed/seti-ui#352] opened 2016-10-31 07:10 UTC
I like seti-icon , and can we add the vuejs icon(xxx.vue)? 
http://vuejs.org/

the icon svg file link:
https://upload.wikimedia.org/wikipedia/commons/5/53/Vue.js_Logo.svg

**Comment by kosciak9** [comment] 2016-11-07 22:47
Duplicate of #316. :)

**Comment by jesseweed** [comment] 2018-08-07 02:37
This icon has been added.

**Closed by jesseweed** 2018-08-07 02:37 UTC
Labels: enhancement, feature request, icon
