### ISSUE TITLE
New icons cause existing icon issues with update of running atom instance

### ISSUE THREAD

**Issue by daynekilheffer** [jesseweed/seti-ui#307] opened 2016-06-10 13:40 UTC
I normally don't shutdown Atom all that often.  One thing I've noticed is that certain updates to the seti-ui theme cause my icons to go out-of-whack.

Introduction of new icons increment the value (`'\E001'`, `'\E002'`) used for each subsequent icon in `styles/_fonts/seti.less`.  It seems that parts of the theme are reloaded by atom in real-time (the less file I assume) while dependencies are not (svgs).

Steps to recreate:
1. clone seti-ui
2. link seti-ui
3. start atom
4. duplicate `icons/apple.svg` as `icons/apple1.svg`
5. run gulp icons
6. view icons in file-types/

Each icon will be off by 1 index

**Comment by jesseweed** [comment] 2016-12-03 22:51
I've seen this as well @daynekilheffer, unfortunately I don't think there's much that be done about it aside from restarting atom if the icon font changes. I'm not sure the cause, I'm guessing some kind of caching, but in any case, when the theme is reloaded, it doesn't seem to reload the icon font.

I'm open to suggestions if you have ideas on a fix. Otherwise, will close this as wont fix for now as I'm not it can be fixed on the theme side.

**Closed by jesseweed** 2016-12-03 22:51 UTC
Labels: icon
