### ISSUE TITLE
Deprecated selector in `seti-ui/index.less`

### ISSUE THREAD

**Issue by dsifford** [jesseweed/seti-ui#364] opened 2016-12-03 17:05 UTC
In `seti-ui/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow atom-overlay` => `atom-text-editor.editor atom-overlay`

* `atom-text-editor::shadow atom-overlay atom-text-editor[mini]` => `atom-text-editor.editor atom-overlay atom-text-editor[mini]`

* `atom-text-editor::shadow atom-overlay atom-text-editor[mini] .text.plain` => `atom-text-editor.editor atom-overlay atom-text-editor[mini] .syntax--text.syntax--plain`

* `atom-text-editor::shadow atom-overlay atom-text-editor[mini] .highlights .highlight.selection .region` => `atom-text-editor.editor atom-overlay atom-text-editor[mini] .highlights .highlight.selection .region`

* `atom-text-editor::shadow atom-overlay atom-text-editor[mini] .lines .cursors .cursor` => `atom-text-editor.editor atom-overlay atom-text-editor[mini] .lines .cursors .cursor`

* `atom-text-editor::shadow atom-overlay .corrections` => `atom-text-editor.editor atom-overlay .corrections`

* `atom-text-editor::shadow atom-overlay .list-group` => `atom-text-editor.editor atom-overlay .list-group`

* `atom-text-editor::shadow atom-overlay .list-group li` => `atom-text-editor.editor atom-overlay .list-group li`

* `atom-text-editor::shadow atom-overlay .autocomplete-suggestion-list .list-group .selected` => `atom-text-editor.editor atom-overlay .autocomplete-suggestion-list .list-group .selected`

* `atom-text-editor::shadow atom-overlay .autocomplete-suggestion-list .list-group` => `atom-text-editor.editor atom-overlay .autocomplete-suggestion-list .list-group`

* `atom-text-editor::shadow atom-overlay .corrections .list-group .selected` => `atom-text-editor.editor atom-overlay .corrections .list-group .selected`

* `atom-text-editor::shadow atom-overlay .corrections .list-group .selected:before` => `atom-text-editor.editor atom-overlay .corrections .list-group .selected:before`

* `atom-text-editor::shadow atom-overlay .corrections .list-group .selected::before,
atom-text-editor::shadow atom-overlay .corrections .list-tree .selected::before` => `atom-text-editor.editor atom-overlay .corrections .list-group .selected::before,
atom-text-editor.editor atom-overlay .corrections .list-tree .selected::before`

* `atom-text-editor::shadow atom-overlay .error-message` => `atom-text-editor.editor atom-overlay .error-message`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by jesseweed** [comment] 2016-12-03 22:15
Thanks @dsifford! I'm working on a 1.13 update to address the shadow dom changes which should take care or the deprecation warnings. I haven't pushed anything yet as 1.13 is still in beta, but may decide to do a pre-release update targeting > 1.12.

**Comment by dsifford** [comment] 2016-12-03 22:17
@jesseweed You rule! 😄

**Comment by jesseweed** [comment] 2016-12-03 22:23
Closing as duplicate of #355

**Closed by jesseweed** 2016-12-03 22:23 UTC
Labels: duplicate

**Comment by inspiredmac** [comment] 2017-01-12 22:07
I'm trying to understand how "issues" work. Apparently this issue is closed as of Dec 3, 2016. When I open Atom (Jan 12, 2016) the same deprecated selector is being flagged  by Deprecation Cop. seti-syntax and sets-syntax/index.less are apparently still issues. Should I just change my theme?

**Comment by dsifford** [comment] 2017-01-12 22:20
@inspiredmac Per @jesseweed, this issue is closed because it is a duplicate of the same issue reported at an earlier time. 

That issue is still open. You can follow along with the progress here: #355

**Comment by vasiliy0s** [comment] 2017-02-01 06:24
+
