### ISSUE TITLE
transition bottom border on tabs and UI changes

### ISSUE THREAD

**Issue by haraldox** [jesseweed/seti-ui#241] opened 2016-05-02 10:07 UTC
great work & congrats on 1.0!! 👍 
thanks a million for SETI UI. after seeing it, you never go back ;)

improvements:
- would it be possible to disable the transition on switching tabs, distracts my eyes ;)

bugs (see screenshot):
- file icons in tabs are cropped
- filenames are "superscript"

noticed changes:
- tree view font size and padding is larger in compact mode... since there seems to be interest in more aerated of UI tweaks, kindly make that available as a setting as well! :)

![screen shot 2016-05-02 at 12 06 15](https://cloud.githubusercontent.com/assets/135914/14952211/e565c6ce-105e-11e6-884b-06ad3c20009f.png)

**Comment by haraldox** [comment] 2016-05-02 10:14
alternatively: please let us know how to customize your styles, since I'm guessing there will be lots of requests coming in, making it quite tiresome to cater to all tastes...

i don't wanna start hacking and hard-coding stuff, if it breaks on every update ;)

thanks for your ongoing efforts! :)

**Comment by haraldox** [comment] 2016-05-02 10:22
even naming related style files would help, so we can diff the legacy version with 1.0 and revert to the styles we liked better :)

i don't want to revert entirely to the old version, since it would mean passing on updates ;)

**Comment by jesseweed** [comment] 2016-05-02 17:47
Hey @haraldox, yeah I can adding the tab transition style to settings.

Are you using [file-icons](https://atom.io/packages/file-icons) plugin per chance? I notice you have a different css icon that seti has, and that package is usually what causes issues issues with icons getting cropped & aligned weirdly. Eiether uninstall that package, or disable seti file icons in settings and it should fix that issue.

Not sure what you mean by "tree view font size and padding is larger in compact mode". Compact mode should definitely be less padding (and i think a slightly smaller font). Perhaps a screenshot would help.

As far as customizing styles, I'm not 100% sure what you're asking, but I would recommend making any changes in your user style sheet so they don't get overridden.

**Comment by jesseweed** [comment] 2016-05-10 07:10
@haraldox I've added a new setting to disable animations. I believe the rest of the bugs are caused by file-icons, so going to go ahead and close this out. Let me know if you still experience any of these issues after updating and viewing the above comment.

**Closed by jesseweed** 2016-05-10 07:10 UTC
