### ISSUE TITLE
Sidebar compact mode lost after restart

### ISSUE THREAD

**Issue by NerdPad** [jesseweed/seti-ui#250] opened 2016-05-02 19:08 UTC
When compact mode is selected the sidebar folder height is reduced, but they reset after restarting atom.

Can anyone please verify, if this is happening for you as well. Just want to make sure it's not caused by any other package.

**Comment by jesseweed** [comment] 2016-05-02 23:35
Hmm, I think I have a good idea what's causing this. Stand by...

**Comment by jesseweed** [comment] 2016-05-10 07:07
@NerdPad Can you confirm if this is still happening after updating to 1.1? I cannot reproduce, so I'm hoping it's gone away.

**Comment by jesseweed** [comment] 2016-05-18 20:51
This should be fixed as of 1.2. Feel free to re-open is you still have an issue.

**Closed by jesseweed** 2016-05-18 20:51 UTC
