### ISSUE TITLE
Tab icons position.

### ISSUE THREAD

**Issue by StiveAZ** [jesseweed/seti-ui#363] opened 2016-12-03 16:30 UTC
Hi Jesse Weed; first good job i like too much Seti UI, and second i have a comment, the icons in the tabs have an offset, i attach one screenshot, my OS is w10.

![seti-ui](https://cloud.githubusercontent.com/assets/8866333/20860686/e68f3120-b94b-11e6-8a89-08b5f18a7c9b.png)

 ;)

Thank's.

**Comment by jesseweed** [comment] 2016-12-03 22:19
Thanks @StiveAZ. Closing this as a dupe of #362. Follow along there for an update.

**Closed by jesseweed** 2016-12-03 22:19 UTC
