### ISSUE TITLE
Fuzzy finder: long paths outside result's box

### ISSUE THREAD

**Issue by Cactucs** [jesseweed/seti-ui#277] opened 2016-05-10 19:51 UTC
![selection_236](https://cloud.githubusercontent.com/assets/4283010/15160216/eee91c64-16f8-11e6-9a1d-638c5eefd3e6.png)

Proposed solutions: 
 - Trim log paths (e.g. show only first X chars)
 - Make the result's "box" bigger/heigher (results in different heights - might be confusing)

**Comment by jesseweed** [comment] 2016-05-10 23:19
This is a duplicate of #259. Thanks!

**Closed by jesseweed** 2016-05-10 23:19 UTC
