### ISSUE TITLE
Deprecated selector in `seti-ui\index.less`

### ISSUE THREAD

**Issue by tonesto7** [jesseweed/seti-ui#375] opened 2017-01-10 20:19 UTC
In `seti-ui\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow atom-overlay` => `atom-text-editor.editor atom-overlay`

* `atom-text-editor::shadow atom-overlay atom-text-editor[mini]` => `atom-text-editor.editor atom-overlay atom-text-editor[mini]`

* `atom-text-editor::shadow atom-overlay atom-text-editor[mini] .text.plain` => `atom-text-editor.editor atom-overlay atom-text-editor[mini] .syntax--text.syntax--plain`

* `atom-text-editor::shadow atom-overlay atom-text-editor[mini] .highlights .highlight.selection .region` => `atom-text-editor.editor atom-overlay atom-text-editor[mini] .highlights .highlight.selection .region`

* `atom-text-editor::shadow atom-overlay atom-text-editor[mini] .lines .cursors .cursor` => `atom-text-editor.editor atom-overlay atom-text-editor[mini] .lines .cursors .cursor`

* `atom-text-editor::shadow atom-overlay .corrections` => `atom-text-editor.editor atom-overlay .corrections`

* `atom-text-editor::shadow atom-overlay .list-group` => `atom-text-editor.editor atom-overlay .list-group`

* `atom-text-editor::shadow atom-overlay .list-group li` => `atom-text-editor.editor atom-overlay .list-group li`

* `atom-text-editor::shadow atom-overlay .autocomplete-suggestion-list .list-group .selected` => `atom-text-editor.editor atom-overlay .autocomplete-suggestion-list .list-group .selected`

* `atom-text-editor::shadow atom-overlay .autocomplete-suggestion-list .list-group` => `atom-text-editor.editor atom-overlay .autocomplete-suggestion-list .list-group`

* `atom-text-editor::shadow atom-overlay .corrections .list-group .selected` => `atom-text-editor.editor atom-overlay .corrections .list-group .selected`

* `atom-text-editor::shadow atom-overlay .corrections .list-group .selected:before` => `atom-text-editor.editor atom-overlay .corrections .list-group .selected:before`

* `atom-text-editor::shadow atom-overlay .corrections .list-group .selected::before,
atom-text-editor::shadow atom-overlay .corrections .list-tree .selected::before` => `atom-text-editor.editor atom-overlay .corrections .list-group .selected::before,
atom-text-editor.editor atom-overlay .corrections .list-tree .selected::before`

* `atom-text-editor::shadow atom-overlay .error-message` => `atom-text-editor.editor atom-overlay .error-message`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by bpjones** [comment] 2017-01-12 01:34
Duplicate of #355

**Comment by V1rtus** [comment] 2017-01-23 07:08
Same!

**Comment by gobinda168** [comment] 2017-01-30 21:42
same

**Comment by jistro** [comment] 2017-02-03 00:08
same

**Comment by abdialeh** [comment] 2017-02-03 02:37
same. What the solution?

**Comment by jesseweed** [comment] 2017-02-03 07:12
Hi all, sorry for the long delay! I've just pushed v1.6 which should finally solve the deprecation issues. Please let me know if you find any issues.

**Closed by jesseweed** 2017-02-03 07:12 UTC

**Comment by supermacyZone** [comment] 2017-02-14 03:14
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

atom-text-editor::shadow atom-overlay => atom-text-editor.editor atom-overlay
atom-text-editor::shadow atom-overlay atom-text-editor[mini] => atom-text-editor.editor atom-overlay atom-text-editor[mini]
atom-text-editor::shadow atom-overlay atom-text-editor[mini] .text.plain => atom-text-editor.editor atom-overlay atom-text-editor[mini] .syntax--text.syntax--plain
atom-text-editor::shadow atom-overlay atom-text-editor[mini] .highlights .highlight.selection .region => atom-text-editor.editor atom-overlay atom-text-editor[mini] .highlights .highlight.selection .region
atom-text-editor::shadow atom-overlay atom-text-editor[mini] .lines .cursors .cursor => atom-text-editor.editor atom-overlay atom-text-editor[mini] .lines .cursors .cursor
atom-text-editor::shadow atom-overlay .corrections => atom-text-editor.editor atom-overlay .corrections
atom-text-editor::shadow atom-overlay .list-group => atom-text-editor.editor atom-overlay .list-group
atom-text-editor::shadow atom-overlay .list-group li => atom-text-editor.editor atom-overlay .list-group li
atom-text-editor::shadow atom-overlay .autocomplete-suggestion-list .list-group .selected => atom-text-editor.editor atom-overlay .autocomplete-suggestion-list .list-group .selected
atom-text-editor::shadow atom-overlay .autocomplete-suggestion-list .list-group => atom-text-editor.editor atom-overlay .autocomplete-suggestion-list .list-group
atom-text-editor::shadow atom-overlay .corrections .list-group .selected => atom-text-editor.editor atom-overlay .corrections .list-group .selected
atom-text-editor::shadow atom-overlay .corrections .list-group .selected:before => atom-text-editor.editor atom-overlay .corrections .list-group .selected:before
atom-text-editor::shadow atom-overlay .corrections .list-group .selected::before, atom-text-editor::shadow atom-overlay .corrections .list-tree .selected::before => atom-text-editor.editor atom-overlay .corrections .list-group .selected::before, atom-text-editor.editor atom-overlay .corrections .list-tree .selected::before
atom-text-editor::shadow atom-overlay .error-message => atom-text-editor.editor atom-overlay .error-message
Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by supermacyZone** [comment] 2017-02-14 03:14
I am getting deprecation issue.

**Comment by jesseweed** [comment] 2017-02-14 05:02
@supermacyZone which version are you running. These should have been fixed in the 1.1.2 update.
