### ISSUE TITLE
Using `Custom Icons` option creates a misalignment on the `Project` Panel

### ISSUE THREAD

**Issue by bsarrant** [jesseweed/seti-ui#467] opened 2018-02-05 09:24 UTC
Hi All,

Following the upgrade to the 1.10.0 version, I discovered that using the `Custom Icons` create a strong height misalignment on the `Project` part, which didn't exist on former versions.

The main consequence is that using this option on project with lots of files, it extends the project height consequently despite the `Compact` option (see screenshots below). 

* Before actioning `Custom Icons`:

![screen shot 02-05-18 at 10 09 am 002](https://user-images.githubusercontent.com/7543583/35796684-9cb416ba-0a5d-11e8-90e9-19e39ad0bd12.PNG)

* After actioning `Custom Icons`

![screen shot 02-05-18 at 10 10 am](https://user-images.githubusercontent.com/7543583/35796733-c1de7296-0a5d-11e8-8010-66864355d711.PNG)

I reproduced this issue on two PCs: one on Windows 7 and the other on Windows 10

Regarding the `Dev console`, I get the same error pattern (exclude the `Git` error) **when starting atom only**

![screen shot 02-05-18 at 10 16 am](https://user-images.githubusercontent.com/7543583/35796780-e1249be4-0a5d-11e8-86f4-eba9c77d4f50.PNG)

**Comment by TsvetomirGeorgiev** [comment] 2018-02-05 10:03
I'm experiencing the same problem using custom icons.

**Comment by rshelnutt** [comment] 2018-02-05 15:01
Confirming above. Custom icons option creating large space between listed objects.

**Comment by cristian-sima** [comment] 2018-02-05 16:29
Same here

**Comment by esechres** [comment] 2018-02-05 21:26
Use the command line:
apm install <package>[@package_version]
apm install seti-ui@1.9.0

**Comment by jbcoder** [comment] 2018-02-06 01:30
Same...

**Comment by BristolITDave** [comment] 2018-02-07 10:15
Following. Literally just installed Atom today, along with Seti-UI. Have turned off custom icons as a nice easy fix.

**Comment by rshelnutt** [comment] 2018-02-09 17:39
Played around in dev mode, can confirm it's being caused by the 'seti' font being used for the icons. Character dimensions causing line break at the `span.name.icon.icon-file-text::before` pseudo

**Comment by Atanacius** [comment] 2018-02-13 00:06
Yeah, I experiment also that error glitch...
Top of that, it's ugly... and unpratical..

Hahaha..

Anyway, is there any solution other than install previous version of Seti-UI ?

**Comment by cristian-sima** [comment] 2018-02-20 12:04
@jesseweed Can you do something? It is really fustrating... :( Thanks

**Comment by jesseweed** [comment] 2018-02-21 16:46
Hi sorry guys, I somehow turned my repo notification off, so just catching up on this. 

The custom icon options does add slightly more padding, but it shouldn't be _that_ much.

I will continue to troubleshoot, but so far I cannot reproduce it on any of my machines.

If anybody is able to pinpoint the cause, I'm happy to put in a fix.

Bonus point if you submit a PR with the fix ;)

**Comment by jesseweed** [comment] 2018-02-21 16:51
Out of curiosity, is everybody experiencing this issue on a Windows machine?

**Comment by bsarrant** [comment] 2018-02-21 16:54
That's my case: all the tests I proceeded in my initial post were on Windows 7 & Windows 10

**Comment by muram** [comment] 2018-02-21 17:07
@jesseweed I'm running Windows 10 with Atom version 1.24.0

**Comment by esechres** [comment] 2018-02-21 17:08
I'm on Windows 10. The 1.9.0 version works and the 1.10.1 version adds an unacceptible padding.  I've rolled back to 1.9.0 until a version (for Windows) doesn't add excessive padding.

**Comment by BristolITDave** [comment] 2018-02-22 09:36
Well, that looks like a Windows issue then :) Same here.

**Comment by Rellek** [comment] 2018-02-22 19:30
Experiencing the same issue.  I love the custom icons for this theme so I rolled back to 1.9.0 for the time being.

**Comment by captain-awesome** [comment] 2018-02-26 21:23
I too am experiencing this spacing issue. Please advise on how to revert back on Windows 10?
Any help is appreciated

**Comment by jbcoder** [comment] 2018-02-26 22:06
@captain-awesome Check out the comment above (https://github.com/jesseweed/seti-ui/issues/467#issuecomment-363226630)

**Comment by jesseweed** [comment] 2018-02-28 04:48
Ok sounds like this is specifically a windows problem. I'll try and get a windows machine and do some testing, I'll let you know when I push an update.

**Comment by cristian-sima** [comment] 2018-03-01 17:04
Nothing yet :( ?

**Comment by Mootly** [comment] 2018-03-05 14:12
Swapping out **just** the seti font files for an older version of the same fixes the problem. (Admittedly, at the cost of scrambling all the icons.) Perhaps simply rebuilding the new font files will fix the problem?

**Comment by OneBeatxdd** [comment] 2018-03-06 05:11
Same here with the windows machines TT^TT

**Comment by Mayshinlyan** [comment] 2018-03-12 18:56
same here with the windows. The problem still exists. Any updates?

**Comment by muram** [comment] 2018-03-14 16:01
@jesseweed any update on the fix?

**Comment by cristian-sima** [comment] 2018-03-15 08:15
@muram nobody cares about us :( 

@jesseweed any hope?

**Comment by TsvetomirGeorgiev** [comment] 2018-03-15 08:58
@muram and @cristian-sima, this is an open source project and every contributor is investing his/her own time without any benefit expectation. I think that you would be more than welcome to submit a PR for fixing the issue. In the mean time, is there something particular that you need from the latest version or you cannot live with "1 pending update"?

 I'm sure that when someone has un update you will get a notification and there is no need to ask for one twice a day..

I apologise if my tone is being rude but this is going out of control. 

P.S. I'm sorry for my crappy english

**Comment by Mootly** [comment] 2018-03-15 11:59
Reminder, to roll back to version 1.9, execute the following in the command line:
```
apm install seti-ui@1.9.0
```
Or, more generically: apm install [@package_version]

Then the problem goes away, as it does by turning off custom icons for the interval.

**Comment by Mootly** [comment] 2018-03-15 14:01
@jesseweed - It looks like the bug in the font file might be the new etherium icon. Got the font height to render correctly in the font viewer when I overwrote it. Don't have the tools to rebuild the font properly tho.

**Comment by Mootly** [comment] 2018-03-15 14:43
Not a real fix because all I did was replace the etherium icon with the eslint icon, but these are the font files I could recreate. Dropped them into seti-ui/styles/fonts/seti/ and I can run 1.10.0 with proper line-heights.

[seti.zip](https://github.com/jesseweed/seti-ui/files/1815776/seti.zip)

**Comment by muram** [comment] 2018-03-15 15:08
@TsvetomirGeorgiev I don't believe that the new update is essential to my day-to-day work and I can live without it, no problem. Is just a habit to have the latest updates installed if possible :)

I agree with you, we should be focusing on solving and contributing to this project as a community. I will do my best (when I've the time) to look into it and provide any feedback/PR if I can find a permanent solution.

Thank you @jesseweed for this awesome theme.

**Comment by chroda** [comment] 2018-04-06 18:03
Hello everyone, would be nice to close these duplicated issues and we propose a patch to fix this.
@jesseweed what u think?

**Comment by jesseweed** [comment] 2018-07-31 05:27
Hi all, sorry for delays on this! Finally got a Windows machine and am able to reproduce. Will take a look at the above PR  and try to get a fix in shortly.

**Comment by xCranberry** [comment] 2018-08-02 08:05
Any news on the fix? <3

**Comment by jesseweed** [comment] 2018-08-06 04:30
Ok this should finally be fixed in 1.11.0!

**Closed by jesseweed** 2018-08-06 04:30 UTC
