### ISSUE TITLE
Tree-View Item Height

### ISSUE THREAD

**Issue by antoniomsfreitas** [jesseweed/seti-ui#469] opened 2018-02-06 11:14 UTC
![menuleft](https://user-images.githubusercontent.com/16882964/35856619-7b60f4fc-0b2e-11e8-8628-0834e0cafaf3.png)

**Comment by jbcoder** [comment] 2018-02-06 19:25
Duplicate of #467

**Comment by jesseweed** [comment] 2018-02-21 16:48
Closing as duplicate of #467.

**Closed by jesseweed** 2018-02-21 16:48 UTC
