### ISSUE TITLE
Failed to activate the seti-ui theme

### ISSUE THREAD

**Issue by akkroopierrebaron** [jesseweed/seti-ui#179] opened 2015-06-08 12:23 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [seti-ui](https://github.com/jesseweed/seti-ui) package, v0.7.1

### Stack Trace

Failed to activate the seti-ui theme

```
At .btn-background is undefined in /Users/pierrebaron/.atom/packages/seti-ui/styles/panels.less:66:4

LessError: .btn-background is undefined
  at /Users/pierrebaron/.atom/packages/seti-ui/styles/panels.less:66:4
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
seti-syntax, v0.4.0

# Dev
No dev packages
```

**Comment by jesseweed** [comment] 2016-03-30 12:01
I haven't seen any action on this in a while, and cannot reproduce to closing this out.

**Closed by jesseweed** 2016-03-30 12:01 UTC
Labels: bug

**Comment by PointedEars** [comment] 2016-09-11 09:25
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [seti-ui](https://github.com/jesseweed/seti-ui) package, v1.3.2


### Stack Trace

Failed to activate the seti-ui theme

```
At '_fonts/roboto.less' wasn't found in /Users/tholah/.atom/packages/seti-ui/index.less:4:0

LessError: '_fonts/roboto.less' wasn't found
  at /Users/tholah/.atom/packages/seti-ui/index.less:4:0
```

### Commands

```
     -0:35 settings-view:open (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
  7x -0:34.1.0 blur (atom-text-editor.editor.vim-mode-plus.insert-mode.is-focused)
     -0:22.7.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:19.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -0:16.2.0 blur (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "seti-ui": {
    "themeColor": "Steel"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.11 (active)
atom-css-comb, v3.1.0 (inactive)
atom-css-unit-converter, v1.1.1 (inactive)
atom-jshint, v2.0.0 (active)
atom-qunit-snippets, v1.1.0 (active)
atom-shell-commands, v1.4.1 (active)
atom-sort-projects, v1.6.0 (active)
atom-ternjs, v0.15.0 (active)
atom-x, v0.4.0 (inactive)
atomatigit, v1.5.5 (active)
auto-detect-indentation, v1.2.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-html-entities, v0.1.0 (active)
autocomplete-paths, v1.0.2 (active)
autoupdate-packages, v1.3.1 (active)
break-time, v0.3.0 (active)
browser-plus, vundefined (active)
character-table, v0.4.3 (active)
clipboard-plus, v0.5.1 (active)
color-picker, v2.2.2 (active)
column-select, v0.2.0 (active)
compare-files, v0.8.0 (active)
css-snippets, v1.0.0 (active)
css-specificity, v0.2.2 (active)
ctrl-last-tab, v0.3.0 (active)
docblockr, v0.8.5 (active)
docs-snippets, v0.8.0 (active)
es6-javascript, v1.0.0 (inactive)
ex-mode, v0.13.0 (inactive)
ex-mode-sort, v1.0.0 (active)
file-icons, vundefined (active)
filesize, v0.4.2 (active)
fixmyjs, v1.3.5 (inactive)
fold-comments, v0.6.0 (inactive)
git-blame, v0.4.11 (inactive)
git-clone, v0.1.5 (inactive)
git-control, v0.8.2 (inactive)
git-difftool, v0.2.7 (inactive)
git-go, v1.0.5 (active)
git-hide, v0.1.2 (active)
git-history, v3.2.0 (inactive)
git-log, v0.4.1 (active)
git-plus, v5.16.2 (inactive)
git-projects, v1.17.0 (inactive)
git-status, v0.3.4 (inactive)
git-tabs, v0.3.0 (active)
git-time-machine, v1.5.3 (inactive)
gitignore-snippets, v0.2.5 (inactive)
highlight-selected, v0.11.2 (active)
html2jade-plus, v1.0.0 (inactive)
jade-beautify, v0.1.5 (active)
jade-snippets, v0.5.0 (active)
javascript-snippets, v1.2.1 (active)
js-refactor, v0.7.3 (active)
keyboard-localization, v1.4.18 (active)
keyboard-scroll, v0.4.0 (active)
language-diff, v0.4.0 (active)
language-jade, v0.7.1 (active)
line-count-status, v0.0.3 (active)
lines, v0.13.1 (inactive)
linter, v1.11.16 (active)
linter-csslint, v1.3.2 (active)
linter-htmlhint, v1.3.0 (active)
linter-jade, v0.3.2 (active)
linter-jshint, v2.1.0 (active)
linter-less, v2.6.0 (active)
linter-shellcheck, v1.2.0 (active)
local-history, v3.4.1 (active)
markdown-scroll-sync, vundefined (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-hide, v0.3.0 (active)
minimap-linter, v1.1.1 (active)
minimap-pigments, v0.2.1 (active)
minimap-split-diff, v0.3.1 (active)
multi-cursor-plus, v1.0.3 (inactive)
nav-panel, v0.0.11 (active)
navigate, v0.1.16 (active)
next-occurrence, v0.5.0 (inactive)
nodejs-snippets, v2.0.2 (active)
nuclide, vundefined (active)
open-git-modified-files, v0.2.4 (inactive)
open-recent, v5.0.0 (active)
open-this, v0.2.0 (inactive)
pane-split-moves-tab, v0.1.0 (inactive)
pigments, vundefined (active)
postcss-sorting, v2.7.0 (active)
preview-plus, v1.2.7 (active)
project-folder, v0.2.0 (inactive)
project-view, v0.5.0 (active)
promote-folder-to-project, v2.0.1 (inactive)
refactor, v0.9.2 (active)
regex-tester, v0.2.0 (inactive)
remember-file-positions, v0.2.2 (active)
restore-windows, v0.4.1 (active)
revert-buffer, v0.5.0 (active)
save-session, v0.16.0 (active)
script, v3.9.0 (inactive)
seti-ui, v1.3.2 (inactive)
show-origin, v0.2.0 (inactive)
smart-tab-name, v1.0.5 (active)
snippets-jade, v0.2.1 (active)
sort-lines, v0.14.0 (inactive)
source-preview-jade, v0.1.1 (active)
source-preview-pug, v0.2.0 (active)
split-diff, v1.0.4 (inactive)
stash-tabs, v0.1.0 (active)
Sublime-Style-Column-Selection, v1.7.2 (active)
symbols-tree-view, v0.13.2 (active)
tab-smart-sort, v0.1.4 (active)
text-manipulation, v0.6.0 (active)
todo-show, v1.7.0 (inactive)
tree-view-git-branch, v0.1.2 (active)
tree-view-git-status, v1.1.0 (active)
up2date, v0.1.2 (active)
vim-mode-clipboard-plus, v0.2.0 (active)
vim-mode-plus, v0.54.1 (active)
xkcd-comics, v0.3.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (active)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```
