### ISSUE TITLE
Tree view has too much vertical spacing after updating seti-ui

### ISSUE THREAD

**Issue by RonyNasr** [jesseweed/seti-ui#481] opened 2018-02-27 11:20 UTC
![image](https://user-images.githubusercontent.com/14307250/36725356-c214cc02-1bbe-11e8-90d7-877e17680fa5.png)
This only happens when I select Seti-ui 
seti-ui version: 1.10.0
seti-syntax version: 1.1.3
treeview version: 0.221.3
atom version: 1.24.0

**Comment by Fecony** [comment] 2018-02-27 16:02
Same problem. 

Also "Core" in settings has much space
![seti](https://user-images.githubusercontent.com/36774784/36739342-56376f7e-1be8-11e8-8491-6136a9a4eafa.PNG)

**Comment by KnuTNatioN** [comment] 2018-03-01 09:16
not only the treeview, the settings have this much space, too.

**Comment by Mootly** [comment] 2018-03-01 14:55
Duplicate of #467

**Comment by jesseweed** [comment] 2018-08-07 03:12
This is fixed in 1.11.0.

**Closed by jesseweed** 2018-08-07 03:12 UTC
