### ISSUE TITLE
Big padding on windows 

### ISSUE THREAD

**Issue by shadowroot2** [jesseweed/seti-ui#488] opened 2018-03-29 07:56 UTC
Big padding in treeview files
![seti_ui](https://user-images.githubusercontent.com/9031709/38076911-effb085a-3358-11e8-9e89-e23c463083dd.JPG)

**Comment by Mootly** [comment] 2018-03-30 17:24
Duplicate of #467

**Closed** 2018-07-13 10:55 UTC
