### ISSUE TITLE
Tabs got smaller

### ISSUE THREAD

**Issue by glennlopez** [jesseweed/seti-ui#87] opened 2015-01-27 14:12 UTC
my tabs look awful (got smaller). Not sure if this is a feature or a bug

**Comment by kupoback** [comment] 2015-01-27 14:23
Same thing happened to me this morning. Tabs shrunk and the text is now dark grey. 

[Screenshot of what I'm seeing.](http://i.imgur.com/0dMC2tl.png)

**Comment by MozMorris** [comment] 2015-01-27 14:23
This happened after the upgrade to 0.176.0.

![screen shot 2015-01-27 at 14 22 37](https://cloud.githubusercontent.com/assets/156303/5919903/02a23cf8-a630-11e4-9a87-a82a2fc2e809.png)

**Comment by middric** [comment] 2015-01-27 14:30
This is a duplicate of #85

**Comment by MozMorris** [comment] 2015-01-27 14:32
@middric you're right. @glennlopez close this one?

**Comment by jesseweed** [comment] 2015-01-27 19:43
Closing as duplicate.

**Closed by jesseweed** 2015-01-27 19:43 UTC
Labels: duplicate

**Comment by glennlopez** [comment] 2015-01-27 22:12
thanks. resolved via rollback
