### ISSUE TITLE
Incomplete display of custom icons in file tabs

### ISSUE THREAD

**Issue by Mattri** [jesseweed/seti-ui#366] opened 2016-12-06 07:12 UTC
Custom Icons are displayed incompletely in tabs. They seem to be shifted upwards and the upper part of the Icons is therefore clipped.

**Comment by BlaM** [comment] 2016-12-07 09:28
Just a guess, but maybe this is affecting people (like me) who prefer "Compact Mode" Setting.

**Comment by MFathirIrhas** [comment] 2016-12-07 23:45
I've opened this issue before, https://github.com/jesseweed/seti-ui/issues/362 , and how to fix it is by adding this to **File** -> **Stylesheet** :
`// fixes seti-ui icon position in tabs
atom-workspace.seti-icons .tab-bar .tab .title::before {
  line-height: 36px;
}`

**Comment by BlaM** [comment] 2016-12-08 08:39
This ticked should be closed then.

**Comment by mattalat** [comment] 2016-12-22 23:03
To follow up on @MFathirIrhas 's solution, adding the following to **File > Stylesheet** also does the trick for affected editors:
```
// fixes seti-ui icon position in tabs
atom-workspace.seti-icons .tab-bar .tab .title::before {
  margin-top: 9px;
}
```
Both methods cause icons on the Mac (which are correctly centered) to fall out of line, so these aren't permanent solutions.

**Comment by jesseweed** [comment] 2017-02-03 07:18
Closing this as duplicate of #362.

**Closed by jesseweed** 2017-02-03 07:18 UTC
