### ISSUE TITLE
Compact not working in split pane

### ISSUE THREAD

**Issue by Garnel** [jesseweed/seti-ui#269] opened 2016-05-05 06:24 UTC
Compact mode not working in split split pane

As the screenshot shows, the right pane's tab not shows in compact mode

![image](https://cloud.githubusercontent.com/assets/1658974/15037349/d67c8aba-12cc-11e6-84fd-c213b8e91e84.png)

**Comment by Garnel** [comment] 2016-05-05 06:30
The compact mode works after I recheck the compact setting.

It just not work in the newly created pane

**Comment by michaeljdeeb** [comment] 2016-05-05 16:59
Running into this exact issue. Also, if you close the compact tabs first the whole top bar becomes un-compact.

**Comment by SaladFork** [comment] 2016-05-05 18:20
Dupe of #247?

**Comment by Garnel** [comment] 2016-05-06 07:36
@SaladFork Yeah...

**Comment by jesseweed** [comment] 2016-05-09 17:36
Closing this as a duplicate of #247. Cheers!

**Closed by jesseweed** 2016-05-09 17:36 UTC
Labels: duplicate
