### ISSUE TITLE
Tabs issues with v0.6.2 

### ISSUE THREAD

**Issue by jeffschwartz** [jesseweed/seti-ui#89] opened 2015-01-27 15:32 UTC
When switching theme to seti-ui 0.6.2 the tabs are almost impossible to see:
![set-ui_tabs](https://cloud.githubusercontent.com/assets/271288/5921134/b6fefb30-a60f-11e4-9b0c-dd4cce9610c1.png)
.

**Comment by AntouanK** [comment] 2015-01-27 15:49
Check #85

**Comment by TerrenceLJones** [comment] 2015-01-27 18:21
:+1:

**Comment by jesseweed** [comment] 2015-01-27 19:44
Closing as duplicate of #85.

**Closed by jesseweed** 2015-01-27 19:44 UTC
Labels: duplicate
