### ISSUE TITLE
Project Find Results Spacing is Off

### ISSUE THREAD

**Issue by contygm** [jesseweed/seti-ui#431] opened 2017-06-06 15:36 UTC
<img width="644" alt="screen shot 2017-06-06 at 11 35 40 am" src="https://user-images.githubusercontent.com/19158002/26837799-5dd6f776-4aac-11e7-93bd-daf1ee34ee34.png">

**Comment by cuberoot** [comment] 2017-06-07 00:29
I'm also having the same issue

**Comment by persac** [comment] 2017-06-07 11:54
Duplicate of #427

**Comment by jesseweed** [comment] 2017-06-08 22:59
Closing as dupe of #427. Fix coming shortly.

**Closed by jesseweed** 2017-06-08 22:59 UTC
