### ISSUE TITLE
Support shadow DOM

### ISSUE THREAD

**Issue by ryanshawty** [jesseweed/seti-ui#198] opened 2015-10-30 10:12 UTC
I'm having a issue with Atom 1.1 where having the shadow enabled will cause the cursor to be one position ahead of the actual cursor position, disabling the shadow DOM option fixed this issue.

**Comment by jadengore** [comment] 2015-10-30 18:30
@ryanshawty Thanks for logging this! I've been trying to figure out how to fix this,

**Comment by bbengfort** [comment] 2015-10-30 18:36
+1 on the shadow DOM issue - It's been kind of weird since the Atom 1.1 update. I don't want to switch from Seti - but it's kind of tough to work with that false cursor position.

**Comment by jadengore** [comment] 2015-10-30 18:36
@bbengfort My cursor is completely broken, even when I switched to One Dark. It's crazy.

**Comment by ryanshawty** [comment] 2015-10-30 20:24
Do you have any other plugins or themes that could be causing that issue? I also found I had to restart atom after disabling the theme.

**Comment by CanKer** [comment] 2015-10-31 08:44
I have the same problem, theres no a way to fix this problem yet?

**Comment by ryanshawty** [comment] 2015-10-31 09:55
I don't believe there is, the theme has to be updated to support shadow DOM
I think. I'm busy until Monday but if not fixed by then I'll have a look
for a solution. I need this theme back!

On Saturday, 31 October 2015, Jorge Arturo César Martínez <
notifications@github.com> wrote:

> I have the same problem, theres no a way to fix this problem yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jesseweed/seti-ui/issues/198#issuecomment-152715742>.
>


-- 
Ryan Shaw

http://ryanshaw.co

**Comment by jesseweed** [comment] 2015-11-02 02:38
The cursor issue was actually a problem with seti-syntax which was fixed in the latest update. Feel free to re-open if you still see the issue (or if I misunderstand what the problem is).

**Closed by jesseweed** 2015-11-02 02:38 UTC

**Comment by jadengore** [comment] 2015-11-02 18:38
If any of you are using `atom-innerspace`, that was causing my issue. See squizlabs/atom-innerspace#4
