### ISSUE TITLE
Tree view padding too tall and tab icons missing

### ISSUE THREAD

**Issue by kurtcarpenter** [jesseweed/seti-ui#468] opened 2018-02-06 08:03 UTC
After updating to v1.10.0 on Windows 10, the tree view has extra padding between files (not folders), and none of my tabs have icons.

![files](https://user-images.githubusercontent.com/9683513/35847981-31d304ae-0ad1-11e8-8fff-ee06b427ea63.JPG)
![tab](https://user-images.githubusercontent.com/9683513/35847982-31ed2492-0ad1-11e8-9f04-1fb3e0b3aca1.JPG)

**Comment by Blastius** [comment] 2018-02-06 08:48
Got the exact same issue. I use compact mode and it also shows the same like your screenshots.

**Comment by brett-shenk** [comment] 2018-02-06 21:54
Same for me. I confirmed it was Seti thats causing the issue and not another package or theme.

**Comment by jesseweed** [comment] 2018-02-21 16:48
Closing as duplicate of #467.

**Closed by jesseweed** 2018-02-21 16:48 UTC
