### ISSUE TITLE
Strange spacing between files in Tree View

### ISSUE THREAD

**Issue by Alpha-UMi** [jesseweed/seti-ui#487] opened 2018-03-27 16:52 UTC
I'm using Atom x64 1.25, seti-dark-ui 1.10 on Windows 10. Just after one of the latest Atom's updates (maybe 1.23... now I'm using 1.25) I noticed a strange visualization in the Tree View (see image). There is a lot of space between the files, and not between folders.. That's strange. Obviously this is related to seti-ui because as soon as I change the theme the Tree View appears "normal".

Any idea?

![003](https://user-images.githubusercontent.com/12111917/37981979-6dc5c81c-31ef-11e8-9231-111ecaea4796.jpg)

**Comment by Mootly** [comment] 2018-03-28 14:15
Duplicate of #467

**Comment by jesseweed** [comment] 2018-08-07 03:17
This has been resolved in 1.11.0

**Closed by jesseweed** 2018-08-07 03:17 UTC
