### ISSUE TITLE
Weird text placement in Tab headers

### ISSUE THREAD

**Issue by simbuerg** [jesseweed/seti-ui#298] opened 2016-06-01 10:50 UTC
Hey,

I'm on Atom 1.7.4 and got weird placement of tab headers with the current version of seti-ui. It looks like a newline sneaked itself in ;-).

Example:
![screenshot_small](https://cloud.githubusercontent.com/assets/598281/15707117/413293ba-27f7-11e6-899b-3d3dad27ce4d.png)

**Comment by glasnak** [comment] 2016-06-01 13:19
I have a similar issue, working on CentOS 7 and Atom 1.7.2 and current version of seti ui.
Example:
![atom-bs](https://cloud.githubusercontent.com/assets/2435886/15709754/bc082654-2806-11e6-9618-dc1e1c7d04c6.png)

**Comment by rkichenama** [comment] 2016-06-01 15:06
similar issue, Windows 10 and Atom 1.7.4

![image](https://cloud.githubusercontent.com/assets/1634457/15714519/d47d9d5e-27e8-11e6-8ecb-6784a27b3095.png)

**Comment by RhyCynn** [comment] 2016-06-04 18:43
I'm not sure what the proper protocol is here for posting workarounds, but I had to override the following styles in my styles.less file:

```css
atom-workspace-axis.vertical .tab-bar .tab {
    padding: 17px 30px;
}

atom-workspace.seti-compact atom-workspace-axis.vertical .tab-bar .tab {
    padding: 7px 30px;
}

atom-workspace .tab-bar .tab .title::before {
    margin-top: -2px;
    margin-left: -25px;
}
```

**Comment by jesseweed** [comment] 2016-06-05 18:09
@simbuerg @glasnak @RhyCynn @rkichenama do you guys have the **seti icons** package installed by chance? I don't have this issue, so figured it was probably an additional package causing conflicts. I tried installing several icon packages and with seti icons installed, I was able to reproduce the issue you all are having.

Let me know if disabling that packages fixes things or not. Thanks!

**Comment by simbuerg** [comment] 2016-06-05 20:18
Thanks for the tip. I disabled the package 'shadow' and the layout returned back to normal.
:-)

**Comment by RhyCynn** [comment] 2016-06-05 20:34
seti-icons was the problem, I should have thought of that myself. Thanks for looking into it and sorry I missed something so obvious.

**Comment by jesseweed** [comment] 2016-06-06 10:28
Gonna go ahead and close this out since it seems to be fixed. Let me know if it pops back up.

**Closed by jesseweed** 2016-06-06 10:28 UTC
