### ISSUE TITLE
Seti Tab Icons

### ISSUE THREAD

**Issue by mbarraz** [jesseweed/seti-ui#368] opened 2016-12-15 08:34 UTC
The icons are cut in half in my tab space.

windows 10

**Comment by sim3001** [comment] 2016-12-21 09:45
I also have this issue currently. Icons in the tab space are cut in half.

**Comment by mattalat** [comment] 2016-12-22 20:46
I'm having the same issue. I'm on Windows 10 and the issue started within the past few weeks. 

#366 addresses this problem, for reference.

**Comment by maorefaeli** [comment] 2016-12-27 12:05
i have the same on windows 10

**Comment by naknode** [comment] 2017-01-03 13:40
I, too, am having this issue on Windows 7.

**Comment by deryost** [comment] 2017-01-04 18:21
Same here with Windows 7

**Comment by undesconocido** [comment] 2017-01-15 18:43
Same here, Win10.

**Comment by codyflynnNC** [comment] 2017-01-16 15:55
Same issue here -win7

**Comment by tinyglowstudio** [comment] 2017-01-19 15:09
I have a pull request in. I didn't realize I was duplicating this issue when I created issue #380.

**Comment by jesseweed** [comment] 2017-02-03 07:18
Closing this as duplicate of #362.

**Closed by jesseweed** 2017-02-03 07:18 UTC
