### ISSUE TITLE
Icons offset in tabs

### ISSUE THREAD

**Issue by pgrantmartello** [jesseweed/seti-ui#380] opened 2017-01-17 19:27 UTC
![image](https://cloud.githubusercontent.com/assets/22772150/22036274/e93d0a26-dcc0-11e6-8f6f-44f08e0ef867.png)

Not sure when this changed.

**Comment by jtoselli** [comment] 2017-01-18 14:00
I have the same issue.
Windows 10
Atom 1.13.0 ia32
seti-ui 1.4.0 (custom-icons enabled)
I also tried with the compact mode from the seti-ui config but that didn't fix the issue.
If I disable custom-icons then some tabs loss their icons and the issue remains for the tabs that still have their icons. The Setting tab icon works fine though

**Comment by NiklasStadler** [comment] 2017-01-19 09:41
I have the same issue.
pls fix it.

**Comment by Sturmkeks** [comment] 2017-01-19 09:46
I started having this issue a few weeks ago.
Would be nice if this gets fixed soon.

**Comment by jesseweed** [comment] 2017-02-03 07:19
Closing this as duplicate of #362.

**Closed by jesseweed** 2017-02-03 07:19 UTC
