### ISSUE TITLE
Misaligned Icons in tabs on Windows 10

### ISSUE THREAD

**Issue by thomasvnl** [jesseweed/seti-ui#387] opened 2017-02-03 12:15 UTC
Using Atom 1.13.1 and Seti-UI 1.6.0 (latest at the moment) the icons in the tabs are misaligned as can be seen in the image below. I'm using Seti-UI in conjunction with Seti-Syntax 1.0.1 (also the latest version at the moment). I have no custom styles applied, this is on a clean Atom installation.

![seti-ui-missaligned-icons-in-tabs](https://cloud.githubusercontent.com/assets/2838263/22590983/8b8f0032-ea12-11e6-9b2d-6e772f7d2da2.PNG)

I managed to fix it by changing the `line-height` property of `.tab-bar .tab .title::before` in `styles\icons\tabs.less` from 17px to 35px.

**Comment by Arcanemagus** [comment] 2017-02-09 00:55
Duplicate of #362. (Workaround posted in the comments of that issue)

**Comment by jesseweed** [comment] 2017-03-23 06:17
Closing as duplicate of #362.

**Closed by jesseweed** 2017-03-23 06:17 UTC
