### ISSUE TITLE
Large distance between items in sidebar and missing icons in tabs

### ISSUE THREAD

**Issue by lazar725** [jesseweed/seti-ui#473] opened 2018-02-10 17:15 UTC
I'm using version Atom 1.23.3 on a Windows 7 64-bit machine, and I've noticed 2 issues:

one is that I don't see any icons next to the file names in the top tabs, and the other is that the distance between the items in the sidebar is huge, as you can see in the screenshot below (this is in compact mode by the way):

![atom seti](https://user-images.githubusercontent.com/11555813/36064587-dc2cad8e-0e95-11e8-9243-170a397bab6d.png)

Is there a workaround for these problems?

Thanks.

**Comment by jessy1092** [comment] 2018-02-11 15:59
Have the same issue on windows 10 , atom 1.23.3, seti-ui 1.10.0

**Comment by etylsarin** [comment] 2018-02-11 21:50
Same here with the same setup as @jessy1092

**Comment by jbcoder** [comment] 2018-02-12 21:02
Duplicate of #467

**Comment by jesseweed** [comment] 2018-02-21 16:50
Closing as duplicate of #467.

**Closed by jesseweed** 2018-02-21 16:50 UTC
