### ISSUE TITLE
Custom Icons Bug

### ISSUE THREAD

**Issue by davidsrn** [jesseweed/seti-ui#480] opened 2018-02-22 18:20 UTC
When I enable custom icons the project bar at the left glitches.

Without custom icons:
![image](https://user-images.githubusercontent.com/26973003/36556397-aa82133a-17ca-11e8-90f4-aa86ba36a43b.png)

With custom icons:
![image](https://user-images.githubusercontent.com/26973003/36556408-b409ccd6-17ca-11e8-8e08-777594221a26.png)

I really love this theme, could you fix it?

**Comment by Rellek** [comment] 2018-02-22 19:27
Duplicate of issue #467

**Comment by jesseweed** [comment] 2018-08-07 03:08
This issue has been resolved.

**Closed by jesseweed** 2018-08-07 03:08 UTC
