### ISSUE TITLE
Misalligned icons on Windows after latest update

### ISSUE THREAD

**Issue by aeschli** [jesseweed/seti-ui#369] opened 2016-12-15 09:44 UTC
The same issue as in #366 and #368 is also visible in VSCode

- VSCode uses the seti.woff font
- broken after the latest update
- only broken on Windows 10, works on Mac and Linux
Windows 10:
![image](https://cloud.githubusercontent.com/assets/6461412/21218900/cf81e9bc-c2b2-11e6-90d7-603b45bc4522.png)
Mac:
![image](https://cloud.githubusercontent.com/assets/6461412/21219045/5f76f8dc-c2b3-11e6-8a8a-f58d994904e7.png)

**Comment by aeschli** [comment] 2016-12-15 10:38
It looks like the change occurred with the commit that added the cake icons
https://github.com/jesseweed/seti-ui/commit/ca2330f7c1731ee91d30c61a126c7f807d34b3fa

**Comment by aeschli** [comment] 2016-12-15 13:33
The problem seems to come from the new 'cake.svg' icon. Removing the firth path element ('<path class="st0" d="M-351.2 98.1c-.4.1-.7.2-1.1.3v-134c.4.1.7.1 1.1.2V98.1z"/>') fixes the problem.

**Comment by jesseweed** [comment] 2017-03-23 06:23
Closing as duplicate of #362.

**Closed by jesseweed** 2017-03-23 06:23 UTC
